apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -o customer-service.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: customer
      name: customer
    spec:
      ports:
        - name: "8080"
          port: 8080
          targetPort: 8080
      selector:
        io.kompose.service: customer
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -o customer-service.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: db
      name: db
    spec:
      ports:
        - name: "5432"
          port: 5432
          targetPort: 5432
      selector:
        io.kompose.service: db
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o customer-service.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: customer
      name: customer
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: customer
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o customer-service.yaml
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: customer
        spec:
          containers:
            - env:
                - name: SPRING_DATASOURCE_PASSWORD
                  value: qwer1234
                - name: SPRING_DATASOURCE_URL
                  value: jdbc:postgresql://db:5432/customer
                - name: SPRING_DATASOURCE_USERNAME
                  value: root
                - name: SPRING_JPA_HIBERNATE_DDL_AUTO
                  value: update
              image: customer-spring-boot-test:latest
              name: customer
              ports:
                - containerPort: 8080
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -o customer-service.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: db
      name: db
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: db
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -o customer-service.yaml
            kompose.version: 1.22.0 (955b78124)
          creationTimestamp: null
          labels:
            io.kompose.service: db
        spec:
          containers:
            - env:
                - name: POSTGRES_DB
                  value: customer
                - name: POSTGRES_PASSWORD
                  value: qwer1234
                - name: POSTGRES_USER
                  value: root
              image: postgres:13.3
              name: customer-database
              ports:
                - containerPort: 5432
              resources: {}
          restartPolicy: Always
    status: {}
kind: List
metadata: {}

