version: "3"

services:
  db:
    image: postgres:13.3
    container_name: customer_database
    environment:
      - POSTGRES_DB=customer
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=qwer1234
    ports:
      - 5432:5432
  customer:
    image: customer-spring-boot-test:latest
    container_name: customer
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/customer
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=qwer1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on: 
      - db
    ports:
      - 8080:8080
